name: CI Pipeline

on:
  schedule:
    - cron: '0 5 * * 1' # Poniedziałek o 5:00
  workflow_dispatch:
    inputs:
      firstBoolean:
        description: "Opis parametru"
        required: false
        default: "false"
      enviroment:
        description: "Opis środowiska"
        required: true
        default: "DEV"
      envs:
        description: "Wybierz środowisko"
        required: true
        type: choice
        options:
          - DEV
          - QA
          - STG
          - PROD
        default: DEV

env:
  EXAMPLE_STRING: Hello
  EXAMPLE_BOOLEAN: true
  EXAMPLE_NUMBER: 5

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cleanup workspace
        run: echo "Cleaning up..."

      - name: Custom function
        run: echo "example string to cleanup stage"

  install:
    runs-on: ubuntu-latest
    needs: cleanup
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # lub 24, jeśli dostępna

      - name: Install dependencies
        run: |
          echo "Instalacja pakietów"
          # npm ci

  test:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        test: [ backend-unit, backend-integration, frontend-unit, frontend-e2e ]
    name: Test - ${{ matrix.test }}
    steps:
      - uses: actions/checkout@v4

      - name: Run ${{ matrix.test }} tests
        run: |
          echo "Uruchamiam testy ${{ matrix.test }}"
          # npm run test:${{ matrix.test }}

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        part: [ backend, frontend ]
    name: Build - ${{ matrix.part }}
    steps:
      - uses: actions/checkout@v4

      - name: Build ${{ matrix.part }}
        run: |
          echo "== ${{ matrix.part }} Build =="
          # npm run build:${{ matrix.part }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy via Ansible
        run: |
          echo "Running Ansible"
          # ansible-playbook -i inventory.ini deploy.yml

  release:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Release complete
        run: echo "Publikacja zakończona"
