#version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: sandbox-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "${MONGO_HOST_PORT}:${MONGO_HOST_PORT}"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  mongo-express:
    image: mongo-express:latest
    container_name: sandbox-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_MONGODB_URL: "mongodb://admin:example@mongo:${MONGO_HOST_PORT}/?authSource=admin"
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  postgres:
    image: postgres:16-alpine
    container_name: sandbox-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_HOST_PORT}:${POSTGRES_HOST_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8082:8080

  redis:
    image: redis:7-alpine
    container_name: sandbox-redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 5s
      timeout: 3s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: sandbox-mailhog
    restart: unless-stopped
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025

  gitea:
    image: gitea/gitea:1.22
    container_name: sandbox-gitea
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000"
      - "127.0.0.1:2222:22"
    environment:
      - GITEA__webhook__ALLOWED_HOST_LIST=jenkins
      - GITEA__webhook__SKIP_TLS_VERIFY=true
#      - GITEA__database__DB_TYPE=postgres
#      - GITEA__database__HOST=db:5432
#      - GITEA__database__NAME=gitea
#      - GITEA__database__USER=gitea
#      - GITEA__database__PASSWD=gitea
    volumes:
      - gitea_data:/data
#    depends_on:
#      - postgres

  jenkins:
    build:
      context: .
      dockerfile: images/jenkins.Dockerfile
    container_name: sandbox-jenkins
    restart: no
    networks:
      - jenkins
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: '1'
    ports:
      - "8083:8080"
      - "50001:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro

#  gitlab:
#    image: gitlab/gitlab-ce:latest
#    container_name: gitlab
#    restart: unless-stopped
#    shm_size: '256m'
#    hostname: gitlab
#    ports:
#      - "127.0.0.1:8929:80"   # HTTP GitLaba na porcie 8929 hosta
#      - "127.0.0.1:2289:22"   # SSH GitLaba na porcie 2289 hosta
#      # - "127.0.0.1:8443:443" # jeśli chcesz TLS w samym GitLabie
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        external_url 'http://gitlab:80'
#        gitlab_rails['gitlab_shell_ssh_port'] = 22
#    volumes:
#      - gitlab_config:/etc/gitlab
#      - gitlab_logs:/var/log/gitlab
#      - gitlab_data:/var/opt/gitlab

#  nginx:
#    build:
#      context: ./docker/nginx
#    container_name: sandbox-nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./certbot-web:/var/www/certbot
#      - ./certs:/etc/letsencrypt:ro
#    restart: unless-stopped

#  next:
#    build:
#      context: ./packages/fullstack
#      dockerfile: Dockerfile
#    env_file: [ .env.example ]
#
#    restart: unless-stopped

#  backend:
#    build:
#      context: ./images/backend
#      dockerfile: Dockerfile
#    env_file: [ .env.example ]
#
#    restart: unless-stopped
#    depends_on:
#      postgres:
#        condition: service_healthy
#      redis:
#        condition: service_healthy
volumes:
  #  gitlab_config:
  #  gitlab_logs:
  #  gitlab_data:
  gitea_data:
  jenkins-data:
  jenkins-docker-certs:
  mongo_data:
    driver: local
  pgdata:
  redis-data:
      driver: local
networks:
  jenkins: