### [C]reate user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "confirmPassword": "{{password}}"

}

### [L]ogin user
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"

}

### [L]ogout user
GET {{baseUrl}}/auth/logout
Content-Type: application/json

### [L]ogin user
POST {{baseUrl}}/auth/refresh
Content-Type: application/json
