### Create company
POST {{baseUrl}}/companies
Content-Type: application/json

{
    "name": "broccoli 4",
    "servings": 1
}

###

GET {{baseUrl}}/companies

###

GET {{baseUrl}}/companies/1

###

PATCH {{baseUrl}}/companies/1
Content-Type: application/json

{
  "name": "TEST NAME 2",
  "servings": 3,
  "description": "test"
}

###

DELETE {{baseUrl}}/companies/1
Content-Type: application/json
