### Create company
POST {{baseUrl}}/companies
Content-Type: application/json

{
    "name": "broccoli 4",
    "servings": 1
}

###

GET {{baseUrl}}/companies

###

GET {{baseUrl}}/companies/1

###

PUT {{baseUrl}}/companies
Content-Type: application/json

{
  "id": 3,
  "name": "new name",
  "servings": 3
}

###

DELETE {{baseUrl}}/companies/1
Content-Type: application/json
