### Create Product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "chuj",
  "unit": "kg",
  "amount": 1,
  "dishId": 1
}

###

GET http://localhost:3000/products

###

PUT http://localhost:3000/products
Content-Type: application/json

{
  "id": 1,
  "name": "8===D",
  "unit": "kg",
  "amount": 1,
  "dishId": 1
}

###

DELETE http://localhost:3000/products/1
Content-Type: application/json
