### Create Product
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "chuj",
  "unit": "kg",
  "amount": 1,
  "dishId": 1
}

###

GET {{baseUrl}}/products

###

PUT {{baseUrl}}/products
Content-Type: application/json

{
  "id": 1,
  "name": "8===D",
  "unit": "kg",
  "amount": 1
}

###

DELETE {{baseUrl}}/products/1
Content-Type: application/json
